# Copyright IBM Corp. 2020, 2025
# SPDX-License-Identifier: MPL-2.0

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam

linters-settings:
  gofmt:
    simplify: true

run:
  timeout: 10m
