version: 2.1

workflows:
  ci:
    jobs:
      - lint
      - go-test:
          name: test
          version: "1.17"

executors:
  golang:
    parameters:
      version:
        type: string
      goarch:
        type: string
        default: amd64
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:<<parameters.version>>
    environment:
      TEST_RESULTS_DIR: /tmp/test-results
      GOTRACEBACK: "all"
      GO111MODULE: "on"
      GOMAXPROCS: 2
      GOARCH: <<parameters.goarch>>

jobs:
  lint:
    executor:
      name: golang
      version: "1.17"
    steps:
      - checkout
      - run: go mod download

      # check go fmt output because it does not report non-zero when there are fmt changes
      - run:
          name: check go fmt
          command: |
            files=$(go fmt ./...)
            if [ -n "$files" ]; then
              echo "The following file(s) do not conform to go fmt:"
              echo "$files"
              exit 1
            fi
      - run: |
          PACKAGE_NAMES=$(go list ./...)
          go vet $PACKAGE_NAMES

  go-test:
    parameters:
      version:
        type: string
      goarch:
        type: string
        default: amd64
      args:
        type: string
        default: "-race"
    executor:
      name: golang
      version: <<parameters.version>>
      goarch: <<parameters.goarch>>
    steps:
      - run: go env
      - checkout
      - run: mkdir -p $TEST_RESULTS_DIR
      - run:
          name: run tests
          environment:
            INTEG_TESTS: "yes"
            GOTESTSUM_FORMAT: short-verbose
          command: |
            gotestsum --junitfile ${TEST_RESULTS_DIR}/junit.xml       -- -timeout=240s <<parameters.args>> .
            gotestsum --junitfile ${TEST_RESULTS_DIR}/junit-batch.xml -- -timeout=240s <<parameters.args>> -tags batchtest .

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
