name: hashicorp/mog/ci
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "ghactions-migration"]
    tags: ["*"]

env:
  TEST_RESULTS_DIR: /tmp/test-results

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: check go fmt
      run: |-
        files=$(go fmt ./...)
        if [ -n "$files" ]; then
          echo "The following file(s) do not conform to go fmt:"
          echo "$files"
          exit 1
        fi
    - run: |
        PACKAGE_NAMES=$(go list ./...)
        go vet $PACKAGE_NAMES
  go-test:
    runs-on: ubuntu-latest
    steps:
    - run: go env
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: run tests
      run: |-
        go test -tags batchtest ./...
 