name: hashicorp/mog/ci
on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main", "ghactions-migration"]
    tags: ["*"]

env:
  TEST_RESULTS_DIR: /tmp/test-results

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - name: check go fmt
      run: |-
        files=$(go fmt ./...)
        if [ -n "$files" ]; then
          echo "The following file(s) do not conform to go fmt:"
          echo "$files"
          exit 1
        fi
    - run: |
        PACKAGE_NAMES=$(go list ./...)
        go vet $PACKAGE_NAMES
  go-test:
    runs-on: ubuntu-latest
    env:
      args: "-race"
    steps:
    - run: go env
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
    - run: mkdir -p $TEST_RESULTS_DIR
    - name: run tests
      run: |-
        go install gotest.tools/gotestsum@latest
        gotestsum --junitfile ${TEST_RESULTS_DIR}/junit.xml       -- -timeout=240s ${{ env.args }} .
        gotestsum --junitfile ${TEST_RESULTS_DIR}/junit-batch.xml -- -timeout=240s ${{ env.args }} -tags batchtest .
      env:
        INTEG_TESTS: 'yes'
        GOTESTSUM_FORMAT: short-verbose
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: "/tmp/test-results"
 